# This file contains the extrinsic parameters for the cameras in the system.
# The extrinsic parameters define the position and orientation of each camera relative to a common reference frame.
# Actual values should be determined through calibration and may vary based on the specific setup and environment.

camera_frame_name: "right_fisheye"
position:
  x: 0.0
  y: -0.1
  z: 0.0
rotation:
  qx: 0.009851
  qy: 0.763635
  qz: -0.645498
  qw: 0.009851